apiVersion: v1
appVersion: "1.0"
description: A Helm chart for vue-cli-plugin-moor-init
name: vue-cli-plugin-moor-init
version: 0.1.0
keywords:
  - vue-cli-plugin-moor-init
  - frontend
sources:
  - http://115.29.170.239:8080/svn/7moor-dev/yunkefu/vue-cli-plugin-moor-init
  - http://git.7moor.com/yunkefu/vue-cli-plugin-moor-init
maintainers:
  - name: Jerry Chan
    email: chenjj@7moor.com
engine: gotpl
