apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        server_name default;
        location / {
            root  /www;
            try_files $uri $uri/ /index.html =404;
            index index.html;
        }

        location ~ ^(.*)\/\.svn\/ {
            return 404;
        }

        location /service {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/service;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /action {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/action;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /report {
            proxy_pass http://_http._tcp.report-node.{{ .Values.version.reportNode }}/report;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /kmdoc {
            root   /mnt/app2;
            index  index.html  index.htm;
        }

        location /customerAttach {
            root /data/app2;
        }

        location /commonPic {
            root   /mnt/app2;
        }

        location /socket.io {
            proxy_pass              http://_http._tcp.cc-socket-push.{{ .Values.version.ccSocketPush }};
            proxy_set_header        Upgrade $http_upgrade;
            proxy_set_header        Connection "upgrade";
            proxy_http_version      1.1;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/application {
            proxy_pass http://_http._tcp.uba-server.{{ .Values.version.ubaServer }}/api/application;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /fileUpload {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/fileUpload;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /fileDownload {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/fileDownload;
            proxy_redirect off;
            proxy_set_header X-Real-Ip $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Accel-Limit-Rate 5k;
        }

        location /bigFileDownload {
            proxy_pass http://_http._tcp.cc-doc.{{ .Values.version.ccDoc }}/fileDownload;
            proxy_redirect off;
            proxy_set_header X-Real-Ip $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
            limit_rate 100k;
        }

        location /form {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/form;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /richUpload {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/richUpload;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /imgUpload {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/imgUpload;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /kmUpload {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/kmUpload;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /importAction {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/importAction;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /public {
            proxy_pass http://_http._tcp.cc-server-in.{{ .Values.version.ccServerIn }}/public;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /public2cc {
            proxy_pass http://_http._tcp.yy-server.{{ .Values.version.yyServer }}/public;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /public2yy {
            proxy_pass http://_http._tcp.yy-server.{{ .Values.version.yyServer }}/public;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /action2bill {
            proxy_pass http://_http._tcp.yy-server.{{ .Values.version.yyServer }}/action2bill;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /uba/service {
            proxy_pass http://_http._tcp.uba-server.{{ .Values.version.ubaServer }}/service;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }

        location /uba {
            proxy_pass http://_http._tcp.uba-client.{{ .Values.version.ubaClient }}/;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }
        location /auth/service {
            proxy_pass http://_http._tcp.authcenter.{{ .Values.version.authcenter }}/service;
            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 100m;
        }
    }
kind: ConfigMap
metadata:
  name: vue-cli-plugin-moor-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": "before-hook-creation"
