{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fedocs.name" . }}
  labels:
    app: {{ template "fedocs.name" . }}
    chart: {{ template "fedocs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ template "fedocs.name" . }}
              servicePort: http
{{- end }}
