#!/bin/sh

if [[ "${CI_COMMIT_REF_NAME}" = "master" ]]; then
  NAMESPACE="prod" 
else
  NAMESPACE="dev"
fi

DOCKER_REGISTRY_HOST=${DOCKER_REGISTRY_HOST:-harbor.7moor.com}
DOCKER_IMAGE=${DOCKER_IMAGE:-privatefe/fedocs}

kubectl -n ${NAMESPACE} get deployment fedocs
if [[ $? -ne 0 ]]; then
  exit 1
else
  kubectl -n ${NAMESPACE} set image deployment/fedocs fedocs=$DOCKER_REGISTRY_HOST/$DOCKER_IMAGE:$(cat VERSION)
fi
